remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

title: Bear Classifier Homepage
description: Small proof of concept image classifier for bears.

author:
  name: Evan Stenger